name: test_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # UI & Logic
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1
  modal_progress_hud_nsn: ^0.5.1

  # Network & Data
  dio: ^5.8.0+1
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  get_it: ^8.0.3
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.3

  # Location
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  google_maps_flutter: ^2.11.0
  flutter_compass: ^0.8.1
  app_settings: ^6.1.1

  # Utilities
  intl: ^0.20.2
  segment_display: ^0.5.0
  flutter_pdfview: ^1.4.0
  animated_text_kit: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/pdfs/
    - assets/jsons/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: SemiBoldCairo
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 700
    - family: DataFontFamily
      fonts:
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 700      
